samples:
  - SRR6974023
  - SRR6974024
  
 
  
conditions:
  - CS01
  - CS02
  
  
WORK_DATA:
  /home/dimitri/Documentos/rnaseq_snakemake/rawData/

WORK_QC:
  /home/dimitri/Documentos/rnaseq_snakemake/qcData/

WORK_TRIM:
  /home/dimitri/Documentos/rnaseq_snakemake/trimData/

WORK_KALL:
  /home/dimitri/Documentos/rnaseq_snakemake/kallisto/




